config/routes.rb
Rails.application.routes.draw do
devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }

  root "homes#top"

  get "/home/about" => "homes#about"
  resources :users
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true,
                   length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :books, dependent: :destroy

attachment :profile_image

validates :name, presence: true, uniqueness: true,
                 length: {minimum: 2, maximum: 20}

validates :introduction,
                 length: {maximum: 50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!,except: [:top, :about]

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :current_user, only: [:edit, :update, :destroy]

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="You have creatad book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      flash.now[:error] = @book.errors.full_messages
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path
    else
      flash.now[:error] = @book.errors.full_messages
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice]="Book was successfully destroyed."
    redirect_to books_path
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.where(user_id: @user.id)
    @book.user == current_user
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(@user)
    else
      flash.now[:error] = @user.errors.full_messages
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

private
  def authenticate_user
    @users = current_user.users
    @user = @users.find_by(id: params[:id])
    redirect_to new_user_session_path unless @user
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<%= form_with model:book, local:true do |f| %>
  <div class="form-group">
    <%= f.label :Title %>
    <%= f.text_field :title, class: "col-xs-12" %>
  </div>

  <div class="form-group">
  	<%= f.label :Opinion %>
    <%= f.text_area :body, class: "col-xs-12" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary col-xs-12" %>
  </div>
<% end %>

app/views/books/_error.html.erb
<% if model.errors.any? %>
  <div class="error">
    <h3><%= model.errors.count %> errors prohibited this obj from being saved</h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container ">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h1>Editing Book</h1>
      <%= render 'books/error', model: @book %>
    <div class="menu">
      <%= form_with model:@book, local:true do |f| %>
    <div class="form-group">
     <%= f.label :Title %>
     <%= f.text_field :title, class: "col-xs-12" %>
    </div>
    <div class="form-group">
  	 <%= f.label :Opinion %>
     <%= f.text_area :body, class: "col-xs-12" %>
    </div>
    <%= f.submit "Update Book" %>
    <% end %>
      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
      <% @book.errors.full_messages.each do |message| %>
       <ul>
        <li>
         <%= message %>
        </li>
       </ul>
<% end %>
  </div>
<% end %>
<%= render 'users/user', user: @user %>
  <h2 class="mt-3">New book</h2>
   <%= render 'books/book', book: @book %>
    <div class="col-md-8 offset-md-1">
     <h2>Books</h2>
      <table class="table table-hover table-inverse">
       <thead>
         <tr>
         <th>Title</th>
         <th>Opinion</th>
         <th colspan="3"></th>
         </tr>
    </div>
     </div>
       </thead>
        <tbody>
         <% @books.each do |book| %>
          <tr>
            <td>
             <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 30, 30,fallback: "no_image.jpg"%>
               <% end %>
            </td>
             <td><%= link_to book.title, book_path(book.id) %></td>
             <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h2>Resend confirmation instructions</h2>

<%= form_for(resource, as: resource_name, url: confirmation_path(resource_name), html: { method: :post }) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", value: (resource.pending_reconfirmation? ? resource.unconfirmed_email : resource.email) %>
  </div>

  <div class="actions">
    <%= f.submit "Resend confirmation instructions" %>
  </div>
<% end %>
<%= render "devise/shared/links" %>

app/views/books/show.html.erb
<%= render 'users/user', user: @user %>
 <h2 class="mt-3">New book</h2>
<%= render 'books/book', book: @newbook %>
<div class="col-md-8 offset-md-1" >
  <h2>Book detail</h2>
    <table class="table table-user-show">
      <tbody>
        <tr>
          <td><%= attachment_image_tag @user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg"%></td>
          <td><%= link_to @user.name, user_path(@user) %></td>
          <td><%= link_to @book.title, book_path(@book.id) %></td>
          <td><%= @book.body %></td>
        <td>
          <% if @book.user == current_user %>
          <%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-sm btn-success" %>
          <% end %>
        </td>
        <td>
          <% if @book.user == current_user %>
          <a data-confirm="本当に消しますか？"> 
          </a>
          <%= link_to "Destroy", book_path(@book), class:"btn btn-sm btn-danger", method: :delete %>
          <% end %>
        </td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/homes/about.html.erb
<main>
 <p id="notice"></p>
  <div class="container">
   <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
   </div>
  </div>
</main>
<footer>
 <div class="container mt-5">
  <div class="row">
   <div class="mx-auto">
    <p>CopyRight Infratop.inc</p>
   </div>
  </div>
 </div>
</footer>

app/views/homes/top.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>
</main>
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to "Home", new_user_registration_path, class:"fas fa-home nav-link text-light" %>
          </li>
          <li class="">
            <%= link_to "Users", users_path, class:"fas fa-users nav-link text-light" %>
          </li>
          <li class="">
            <%= link_to "Books", books_path, class:"fas fa-book-open nav-link text-light" %>
          </li>
          <li class="">
            <%= link_to "Log out", destroy_user_session_path, class:"fas fa-sign-out-alt nav-link text-light", method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to "Home", "/", class:"fas fa-home nav-link text-light" %>
          </li>
          <li class="">
            <%= link_to "About", home_about_path, class:"fas fa-link nav-link text-light" %>
          </li>
          <li class="">
            <%= link_to "Sign up", new_user_registration_path, class:"fas fa-user-plus nav-link text-light" %>
          </li>
          <li class="">
            <%= link_to "Log in", new_user_session_path, class:"fas fa-sign-in-alt nav-link text-light" %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
    <main>
      <p class="notice"><%= notice %></p>
    <%= yield %>
  </body>
</html>

app/views/users/_user.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
    <h2>User info</h2>
      <table>
        <%= attachment_image_tag user, :profile_image, :fill, 30, 30,fallback: "no_image.jpg" %>
      <table class="table">
       <tbody>
        <tr></tr>
         <tr>
	        <th>name
	         <th><%= user.name %></th>
	        </th>
	       </tr>
        <tr>
	       <th>introduction<th><%= user.introduction %></th>
        </tr>
       </tbody>
      </table>
  <div class="row">
  <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block fas fa-user-cog" do %>
  <% end %>
</div>

app/views/users/about.html.erb
<h1>Welcom to
  <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
  <b>Bookers!!</b>
</h1> 

app/views/users/edit.html.erb
<% if @user.errors.any? %>
 <div id="error_explanation">
  <h3><%= @user.errors.count %>error prohibited this book from being saved:</h3>
    <% @user.errors.full_messages.each do |message| %>
     <ul>
      <li>
       <%= message %>
      </li>
     </ul>
<% end %>
  </div>
<% end %>
<div class="container ">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h2>User info</h2>
    <%= form_with model: @user, local: true do |f| %>
    <div class = "fprm-group">
      <div class="user-name">Name</div>
       <%= f.text_field :name %>
    </div>
    <div class = "fprm-group">
    <div class="user-edit-image">Image</div>
      <%= f.attachment_field :profile_image %>
    </div>
    <div class = "fprm-group">
    <div>Introduction</div>
      <%= f.text_area :introduction %><br>
    </div>
    <div class="row">
      <%= f.submit "Update User", class:"btn btn-secondary btn-block fas fa-user-cog edit_user" %>
    </div>
      <% end %>
  </div>
 </div>
</div>
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/users/index.html.erb
<%= render 'users/user', user: @user %>
 <h2>New book</h2>
  <%= render 'books/book', book: @book %>
   <div class="col-md-8 offset-md-1">
  	 <table class="table table-sm user-index">
	  	<h2>Users</h2>
       <thead>
        <th>image</th>
        <th>name</th>
        <th></th>
  	   </thead>
  	  <tbody>
  	   <% @users.each do |user| %>
	  	  <tr>
	  	   <td><%= attachment_image_tag user, :profile_image, :fill, 30, 30,fallback: "no_image.jpg"%></td>
	  	   <td><%= user.name %></td>
	  	   <td><%= link_to "Show", "/users/#{user.id}" %></td>
	  	  </tr>
  	   <% end %>
  	  </tbody>
  	 </table>
  	</div>
  </div>

app/views/users/show.html.erb
<%= render 'users/user', user: @user %>
 <h2>New book</h2>
  <%= render 'books/book', book: @book %>
   </div>
    <div class="col-md-8 offset-md-1">
     <table class="table book-index">
      <h2 class="mt-3">Books</h2>
       <thead>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
       </thead>
      <tbody>
       <% @books.each do |book| %>
        <tr>
          <td>
           <%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 30, 30,fallback: "no_image.jpg"%>
       <% end %>
          </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
        </tr>
       <% end %>
      </tbody>
      </table>
    </div>
  </div>
</div>